name: Workflow 1

on:
  workflow_dispatch:
    inputs:
      user_input:
        description: 'User input for prem.txt content'
        required: true
  repository_dispatch:
    types: [trigger-workflow-1]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Check if prem.txt exists and process user input
        run: |
          if [ -f "prem.txt" ]; then
            echo "prem.txt exists"
            if [ "${{ github.event_name }}" = "workflow_dispatch" ]; then
              echo "${{ github.event.inputs.user_input }}" > prem.txt
              git config --global user.name "premkumar2812"
              git config --global user.email "kpremkumar28120@gmail.com"
              git add prem.txt
              git commit -m "Update prem.txt"
              git push
            fi
          else
            echo "prem.txt does not exist"
            if [ "${{ github.event_name }}" = "workflow_dispatch" ]; then
              echo "${{ github.event.inputs.user_input }}" > prem.txt
              git config --global user.name "premkumar2812"
              git config --global user.email "kpremkumar28120@gmail.com"
              git add prem.txt
              git commit -m "Add content to prem.txt"
              git push
            fi
          fi

      - name: Trigger Workflow 2
        uses: peter-evans/repository-dispatch@v1
        with:
          token: ${{ secrets.PAT_TOKEN }}
          repository: premkumar2812/task
          event-type: trigger-workflow-2
