name: Workflow 2

 

on:
  repository_dispatch:
    types: [trigger-workflow-2]

 

jobs:
  build:
    runs-on: ubuntu-latest

 

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Create Dockerfile
        run: |
          # Set the name of your text file in the repository
          TEXT_FILE=prem.txt

          # Generate the Dockerfile content
          DOCKERFILE_CONTENT=$(cat "$TEXT_FILE" | sed 's/^/RUN echo "/; s/$/"/')
          # Save the Dockerfile content to a file
          echo "# Use a base image" > Dockerfile
          echo "FROM ubuntu:latest" >> Dockerfile
          echo "" >> Dockerfile
          echo "# Set the working directory" >> Dockerfile
          echo "WORKDIR /app" >> Dockerfile
          echo "" >> Dockerfile
          echo "# Copy the application code into the container" >> Dockerfile



          # Save the Dockerfile content to a file
          echo "$DOCKERFILE_CONTENT" > Dockerfile

          # Commit and push the generated Dockerfile back to the repository
          git config user.name "premkumar2812"
          git config user.email "kpremkumar28120@gmail.com"
          git add Dockerfile
          git commit -m "Generated Dockerfile from $TEXT_FILE"
          git remote set-url origin "https://github.com/premkumar2812/task.git"
          git push origin main
      - name: Login to docker hub
        uses: docker/login-action@v1

        with:
           username: ${{  secrets.DOCKER_USERNAME  }}
           password: ${{  secrets.DOCKER_PASSWORD  }}
      - name: Build Docker image
        run: |
          docker build -t my-docker-image .
          docker run -d my-docker-image
      - name: List images
        run: |
         docker image ls
         realpath my-docker-image
      - name: Tag image
        run: |
         docker tag my-docker-image:latest premkumar2812/task1:newtag 


      - name: Push Docker image to Docker Hub
        run: |
           docker image push premkumar2812/task1:newtag
