name: Workflow 1

 

on:
  workflow_dispatch:
  repository_dispatch: 
              types: [trigger-workflow-1]


 

jobs:
  build:
    runs-on: ubuntu-latest

 

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

 

      - name: Check if prem.txt exists
        run: |
          if [ -f "prem.txt" ]; then
            echo "prem.txt exists"
            exit 0
          else
            echo "prem.txt does not exist"
            echo "Hello, World!" > prem.txt
            git config --global user.name "premkumar2812"
            git config --global user.email "kpremkumar28120@gmail.com"
            git add prem.txt
            git commit -m "Add content to prem.txt"
            git push
          fi

          
      - name: Trigger Workflow 2
        uses: peter-evans/repository-dispatch@v1
        with:
          token: ${{ secrets.PAT_TOKEN }}
          repository: premkumar2812/task
          event-type: trigger-workflow-2
